"""Stub file for ta (Technical Analysis) library"""
from typing import Any

class momentum:
    class RSIIndicator:
        def __init__(self, close: Any, window: int = 14) -> None: ...
        def rsi(self) -> Any: ...
    
    class MACD:
        def __init__(self, close: Any) -> None: ...
        def macd(self) -> Any: ...
        def macd_signal(self) -> Any: ...
        def macd_diff(self) -> Any: ...

class trend:
    class ADXIndicator:
        def __init__(
            self,
            high: Any,
            low: Any,
            close: Any,
            window: int = 14
        ) -> None: ...
        def adx(self) -> Any: ...
        def adx_pos(self) -> Any: ...
        def adx_neg(self) -> Any: ...
    
    class SMAIndicator:
        def __init__(self, close: Any, window: int) -> None: ...
        def sma_indicator(self) -> Any: ...
    
    class MACD:
        def __init__(self, close: Any) -> None: ...
        def macd(self) -> Any: ...
        def macd_signal(self) -> Any: ...
        def macd_diff(self) -> Any: ...

class volatility:
    class BollingerBands:
        def __init__(
            self,
            close: Any,
            window: int = 20,
            window_dev: int = 2
        ) -> None: ...
        def bollinger_hband(self) -> Any: ...
        def bollinger_mavg(self) -> Any: ...
        def bollinger_lband(self) -> Any: ...

class volume:
    class OnBalanceVolumeIndicator:
        def __init__(self, close: Any, volume: Any) -> None: ...
        def on_balance_volume(self) -> Any: ...
    
    class AccDistIndexIndicator:
        def __init__(
            self,
            high: Any,
            low: Any,
            close: Any,
            volume: Any
        ) -> None: ...
        def acc_dist_index(self) -> Any: ...














